
export const site = {
  name: "Mehak Aggarwal",
  email: "aggarwalmehak2016@gmail.com",
  linkedin: "https://www.linkedin.com/in/seelimsii/",
  github: "https://github.com/seelimsii",
  resumeViewer: "/public/images/documents/mehak-aggarwal-resume.pdf",
  profileImage: "/public/images/profile/mehak.jpg",
  headline: "Computer Science Graduate · Cloud, DevOps & Technology · Business & Analytical Thinking",
  intro:
    "A Computer Science graduate with practical experience across Cloud and DevOps, business-facing technology work, research and leadership. I enjoy working where technical execution, structured problem solving and people or process coordination meet.",
};

export const stats = [
  { value: "United Airlines", label: "Current role" },
  { value: "15+", label: "Projects deployed at Blu Parrot" },
  { value: "5", label: "Leadership / activity organisations featured" },
  { value: "7", label: "Awards & recognitions in resume" },
];

export const focusAreas = [
  {
    title: "Cloud & DevOps",
    text: "Practical exposure to AWS, CI/CD, infrastructure, deployment, monitoring, automation and cloud environments.",
    tags: ["AWS", "Jenkins", "Docker", "Kubernetes", "Terraform", "CloudWatch"],
  },
  {
    title: "Business & Analytics",
    text: "Experience in analyst work, client interaction, process coordination, research and data-oriented problem solving.",
    tags: ["Analysis", "Coordination", "Research", "Documentation", "Power BI"],
  },
  {
    title: "Leadership & Communication",
    text: "Leadership across technical societies, volunteering, design and event coordination, with an emphasis on teamwork and communication.",
    tags: ["Leadership", "Communication", "Teamwork", "Presentation"],
  },
];

export const experience = [
  {
    id: "united-airlines",
    company: "United Airlines India Knowledge Center",
    initials: "UA",
    role: "Associate Analyst",
    dates: "Jul 2026 – Present",
    location: "Gurugram",
    featured: true,
    image: "/public/images/experience/united-airlines-1.jpeg",
    imageAlt: "Mehak at the United Airlines workplace",
    summary: "A direct placement into an analyst role combining business-facing coordination, process understanding and technology-domain exposure.",
    bullets: [
      "Completed Infosys training covering DevOps, AWS, Aviation Domain and Cyber Security.",
      "Shadowed Senior Business Analyst activities directly under supervision.",
      "Separated offshore work from an existing combined onshore/offshore Scrum process so offshore work could be tracked and calculated more effectively.",
      "Maintained records and supported coordination for an offshore team of 8.",
    ],
    skills: ["Business Analysis", "Scrum Coordination", "AWS", "DevOps", "Communication", "Process Coordination"],
  },
  {
    id: "blu-parrot",
    company: "Blu Parrot Ventures",
    initials: "BP",
    role: "DevOps Analyst — Internship",
    dates: "May 2025 – Jul 2025",
    location: "Gurugram, Haryana",
    featured: true,
    image: "/public/images/gallery/blu-parrot.jpeg",
    imageAlt: "Blu Parrot internship memory",
    summary: "Hands-on DevOps ownership across client projects, cloud environments, deployment automation and infrastructure.",
    bullets: [
      "Spearheaded end-to-end deployment of 15+ diverse projects including web apps, ML/LLM models and data scrapers.",
      "Worked across AWS, Azure and GCP environments.",
      "Created a Jenkins server and implemented CI/CD pipelines from scratch, reducing deployment time by 20%.",
      "Collaborated directly with developers and clients while managing infrastructure as the sole DevOps function member.",
      "Managed IT assets using Apexa-IQ.",
    ],
    skills: ["AWS", "Azure", "GCP", "Jenkins", "CI/CD", "Infrastructure", "Monitoring", "Apexa-IQ"],
  },
  {
    id: "zigram",
    company: "ZIGRAM",
    initials: "ZG",
    role: "Technology Intern (AWS Cloud)",
    dates: "Jan 2025 – Mar 2025",
    location: "Gurugram",
    featured: true,
    summary: "Cloud operations and deployment support spanning hybrid cloud, APIs, RDS, monitoring, automation and documentation.",
    bullets: [
      "Worked in hybrid cloud, managing API deployments, flush & fill activities, RDS upgrades, CloudWatch alarms, server monitoring and Jenkins CI/CD.",
      "Used Python scripting and Cloud Shell scripting to speed up operational tasks.",
      "Documented deployment processes and maintained resource data sheets for different services.",
      "Optimized costs through infrastructure analysis and clean-ups.",
    ],
    skills: ["AWS", "RDS", "CloudWatch", "Jenkins", "Python", "Cloud Shell", "Documentation"],
  },
  {
    id: "acorporate-x",
    company: "ACORPORATE X",
    initials: "AX",
    role: "Business Analyst",
    dates: "Apr 2023 – May 2023",
    location: "Delhi, India",
    featured: true,
    summary: "An early business-facing role combining client engagement, outreach, website delivery and cost-conscious technology decisions.",
    bullets: [
      "Managed client relationships and engagement.",
      "Orchestrated stall setup at Daulat Ram College (DRC) to expand website outreach.",
      "Conducted on-call and WhatsApp marketing campaigns to attract new clients.",
      "Delivered the firm's complete website with web hosting and domain mapping.",
      "Researched and implemented cost-effective solutions including free hosting on Netlify and EmailJS for the contact form backend.",
      "Managed data transfer on cloud.",
    ],
    skills: ["Business Analysis", "Client Engagement", "Business Development", "Web Hosting", "Cloud"],
  },
];

export const projects = [
  {
    id: "rice-disease",
    title: "Intelligent Rice Disease Detection & Advisory System",
    category: "AI / ML & Research",
    date: "Jan 2026 – May 2026",
    featured: true,
    summary: "A deep-learning rice leaf disease detection system combined with a generative-AI advisory module and web application.",
    description:
      "The dissertation addressed automated identification of Blast, Brown Spot, Bacterial Blight and Tungro from leaf images, combining image classification with an AI-driven advisory module.",
    role: "Research / Dissertation",
    technologies: ["Deep Learning", "CNN", "Python", "TensorFlow", "Computer Vision", "Generative AI", "Streamlit"],
    highlights: [
      "Developed a CNN-based classification model using the Mendeley Rice Leaf Disease Dataset (Sethy et al.).",
      "Test-set evaluation achieved an overall classification accuracy of 99.32%.",
      "Created and hosted a web application where users can upload or capture a leaf image and receive a disease prediction with confidence.",
      "Added a generative-AI advisory module for treatment recommendations and preventive measures.",
      "The initial systematic literature review identified gaps around dataset limitations, real-world deployment and integrated advisory systems.",
    ],
    links: {
      documentation: "https://docs.google.com/document/d/1pS1OzskEW8tMgwnhBXcLR5h_mmixBY9HPlFvd57gDDE/edit",
      github: "",
      liveDemo: "",
      certificate: "https://drive.google.com/file/d/12N5Ref_IOIqQL0B2pbG_7PTkU83xBnYL/view",
    },
  },
  {
    id: "cloud-native-eks",
    title: "Complete Cloud-Native Infrastructure with Jenkins, Terraform & EKS",
    category: "Cloud & DevOps",
    date: "2025–2026",
    featured: true,
    summary: "A DevOps-focused workflow around an existing open-source Node.js application; my contribution was the infrastructure and DevOps configuration, not the application source code.",
    description:
      "Configured an end-to-end cloud-native delivery workflow around an existing open-source Node.js application, connecting GitHub, Jenkins, Docker, Amazon ECR and Kubernetes on EKS, with AWS infrastructure provisioned through Terraform.",
    role: "DevOps / Cloud Project",
    technologies: ["AWS", "Jenkins", "Terraform", "EKS", "ECR", "Docker", "Kubernetes", "GitHub"],
    highlights: [
      "Automated provisioning of EKS, VPC and ECR infrastructure through Terraform.",
      "Configured Jenkins to respond to GitHub webhooks.",
      "Automated Docker image builds, ECR pushes and Kubernetes deployments.",
      "Established a code-to-deployment workflow for a containerized Node.js application.",
    ],
    links: {
      github: "https://github.com/seelimsii/devops-task/",
      documentation: "",
      liveDemo: "",
      certificate: "",
    },
  },
  {
    id: "jitsi-aws",
    title: "Dockerized Jitsi Meet Deployment on AWS EC2",
    category: "Cloud & DevOps",
    date: "Sep 2024",
    featured: true,
    summary: "Deployment of Jitsi Meet on AWS EC2 using Docker, followed by HTTPS configuration for secure access.",
    description:
      "A DevOps deployment exercise based on the open-source Jitsi Meet project. My contribution focused on the DevOps/configuration files and deployment on AWS EC2 using Docker, followed by HTTPS access.",
    role: "Cloud / DevOps Project",
    technologies: ["AWS EC2", "Docker", "HTTPS"],
    highlights: [
      "Deployed Jitsi Meet on AWS EC2 using Docker.",
      "Configured HTTPS access.",
      "Built practical experience around web hosting and cloud deployment.",
    ],
    links: { github: "", documentation: "https://docs.google.com/document/d/12Y_tqA1OTYkt1hJPzd0d6wJ50i7lOP7MZwRyUeBFXQA/edit", liveDemo: "", certificate: "" },
  },
  {
    id: "jenkins-php",
    title: "DevOps Automation: Jenkins & PHP on AWS EC2",
    category: "Cloud & DevOps",
    date: "Aug 2024",
    featured: true,
    summary: "Automated web hosting and deployment for a PHP website on AWS EC2 using Jenkins.",
    description:
      "A DevOps automation exercise based on an existing open-source PHP web application. My contribution focused on the DevOps files and Jenkins-based deployment on AWS EC2, rather than authoring the application itself.",
    role: "DevOps Project",
    technologies: ["AWS EC2", "Jenkins", "PHP", "GitHub"],
    highlights: [
      "Automated deployment for a PHP website on AWS EC2.",
      "Connected source control and deployment tooling in a practical hosting workflow.",
    ],
    links: { github: "", documentation: "https://docs.google.com/document/d/12Y_tqA1OTYkt1hJPzd0d6wJ50i7lOP7MZwRyUeBFXQA/edit", liveDemo: "", certificate: "" },
  },
  {
    id: "aqi",
    title: "Air Quality Index Prediction Model",
    category: "AI / ML & Research",
    date: "Jan 2024 – May 2024",
    featured: true,
    summary: "A machine-learning project using Indian AQI data from 2015–2020 for prediction and air-quality rating.",
    description:
      "Developed an ML workflow around historical AQI data, including preprocessing and model development for predicting and rating air quality across Indian states.",
    role: "Academic ML Project",
    technologies: ["Python", "Machine Learning", "Data Preprocessing", "Regression"],
    highlights: [
      "Used 2015–2020 AQI data.",
      "Performed data preprocessing and developed a machine-learning model.",
      "Worked on prediction and rating of air quality across Indian states.",
    ],
    links: { github: "https://colab.research.google.com/drive/12cEgrAMRwqvY5ozW5NFd5FGuly85bUc_", documentation: "https://docs.google.com/document/d/1n_A_qZ5PB3RNlYThe5Wymo2HTV1MzH8TRpiH_7wsw_4/edit", liveDemo: "", certificate: "" },
  },
  {
    id: "slr-rice",
    title: "Systematic Literature Review: Machine Learning Methods for Rice Plant Disease",
    category: "Research",
    date: "Jul 2025 – Dec 2025",
    featured: false,
    summary: "A literature review examining machine-learning approaches to rice plant disease detection and identifying research gaps.",
    description:
      "A research review that informed the later rice disease dissertation. My contribution included project work and coordination as a member.",
    role: "Research Member / Coordination",
    technologies: ["Literature Review", "Machine Learning Research", "Research Analysis"],
    highlights: [
      "Reviewed research around machine-learning methods for rice plant disease.",
      "Contributed as a member with coordination and project work.",
      "The review helped identify gaps later addressed in the rice disease dissertation.",
    ],
    links: { github: "", documentation: "https://docs.google.com/document/d/1i_sh9-67iUJsTG7xKbHHKYdoEaC85enHf648IISNFB4/edit", liveDemo: "", certificate: "" },
  },
  {
    id: "placement-review",
    title: "Research Review: Placement Prediction and Analysis",
    category: "Research",
    date: "Jan 2025 – Jun 2025",
    featured: false,
    summary: "A collaborative research review around placement prediction and analysis.",
    description:
      "A team research review in which I contributed as a member with coordination and project work.",
    role: "Research Member / Coordination",
    technologies: ["Research", "Analysis", "Coordination"],
    highlights: [
      "Contributed as a member of the research team.",
      "Supported project coordination and research work.",
    ],
    links: { github: "", documentation: "", liveDemo: "", certificate: "" },
  },
  {
    id: "dark-pattern-buster",
    title: "Dark Pattern Buster Application",
    category: "Hackathon",
    date: "Dec 2023 – Feb 2024",
    featured: false,
    summary: "A hackathon project around identifying dark patterns in digital experiences, for which I received a Certificate of Excellence.",
    description:
      "Participated in DPBH'23, contributing to research, ML model development and content writing for the Dark Pattern Buster mobile application.",
    role: "Research / ML / Content",
    technologies: ["Machine Learning", "Research", "Content Writing"],
    highlights: [
      "Contributed to research and ML model development.",
      "Worked on content writing for the application.",
      "Received a Certificate of Excellence in DPBH'23.",
      "Important: this was not a finalist/winning result; the team was eliminated in the first round.",
    ],
    links: { github: "", documentation: "", liveDemo: "", certificate: "" },
  },
];

export const achievements = [
  {
    id: "research-display",
    title: "2nd Best Research Award at Hansraj College’s Research Display Week",
    issuer: "Hansraj College",
    date: "Jun 2026",
    type: "Research",
    description: "Recognition for the final-year research display of the rice disease detection and advisory project.",
    relatedProject: "rice-disease",
  },
  {
    id: "best-poster",
    title: "Best Poster Presentation",
    issuer: "Sai School of Physical Sciences, Sri Sai University",
    date: "Mar 2026",
    type: "Research",
    description: "Best Poster Presentation for the Intelligent Rice Disease Detection and Advisory System Using Deep Learning at NCAIPS-2026.",
    relatedProject: "rice-disease",
  },
  {
    id: "sih-college",
    title: "SIH'24 Finalist",
    issuer: "Hansraj College / Smart India Hackathon",
    date: "Nov 2024",
    type: "Hackathon",
    description: "A college-level mini round was conducted before ideas were submitted to SIH'24. The team received college recognition and also has SIH-related certification. The project focused on Child Safety and Well-being with a focus on emotional fitness.",
    relatedProject: null,
  },
  {
    id: "yuvamanthan",
    title: "Certificate of Appreciation — Yuvamanthan Hackathon",
    issuer: "Hansraj College",
    date: "Aug 2024",
    type: "Hackathon",
    description: "Participated with an anti-keylogging keyboard/software concept. The project was not fully functional and did not win; the recognition was for participation/contribution.",
    relatedProject: null,
  },
  {
    id: "hunt-it-out",
    title: "1st Position in Hunt It Out",
    issuer: "Shyam Lal College, University of Delhi",
    date: "Mar 2024",
    type: "Competition",
    description: "Stood 1st among 22 teams in Hunt It Out at Yudaspandana Fest, a treasure-hunt style event requiring courage and problem solving.",
    relatedProject: null,
  },
  {
    id: "dpbh",
    title: "Certificate of Excellence — DPBH'23",
    issuer: "IIT-BHU in collaboration with the Ministry of Consumer Affairs",
    date: "Mar 2024",
    type: "Hackathon",
    description: "Received a Certificate of Excellence for contribution to the Dark Pattern Buster mobile application. Not a finalist or winner.",
    relatedProject: "dark-pattern-buster",
  },
  {
    id: "lor",
    title: "Letter of Recommendation from Advocate at Supreme Court",
    issuer: "Ujjwal Gaur",
    date: "Jul 2024",
    type: "Recognition",
    description: "Letter of recommendation associated with leadership and contribution work.",
    relatedProject: null,
  },
];

export const leadership = [
  {
    id: "ordinateur",
    organization: "Ordinateur — The Computer Science Society, Hansraj College",
    role: "Technical Head",
    dates: "Oct 2023 – Sep 2024",
    initials: "OR",
    description: "Technical leadership within the Computer Science society, including team management, event coordination and technical activities.",
    highlights: [
      "Organized and led Code Crash, a hackathon conducted through the society with contributions from the wider team.",
      "Helped conduct Anomaly, a treasure-hunt style event through the society.",
      "Managed and trained technical team members, including beginner-level editing software instruction.",
    ],
  },
  {
    id: "cas",
    organization: "Culinary Arts Society, Hansraj College",
    role: "Technical Head",
    dates: "Jul 2023 – Jun 2024",
    initials: "CAS",
    description: "Technical leadership within the society, following an earlier Technical Team Member role.",
    highlights: [
      "Supported technical activities and team coordination.",
      "Previously contributed as a Technical Team Member and helped conduct Nemesis, a treasure-hunt event involving clues, quizzes and puzzles.",
    ],
  },
  {
    id: "bitwise",
    organization: "Bitwise Vol. 5 Magazine",
    role: "Senior Designer",
    dates: "Aug 2024 – Dec 2024",
    initials: "BW",
    description: "Senior Designer for the fifth edition of Bitwise, the Computer Science department's technology magazine.",
    highlights: [
      "Designed the visual outlook of the magazine.",
      "Managed the designer team.",
      "Collaborated with teachers and past designers.",
      "Supported the editorial team with article refinement.",
    ],
    officialLink: "",
  },
  {
    id: "ehsaas",
    organization: "Ehsaas for Humanity Foundation",
    role: "College President — HRC Unit",
    dates: "Mar 2023 – Apr 2024",
    initials: "EH",
    description: "Led the college unit and coordinated social-impact activities.",
    highlights: [
      "Initiated and led drives including Pashu Aahar, Shikanji and Cloth Donation Drives.",
      "Led the society's operations and member coordination.",
      "Received a Letter of Recommendation from Ujjwal Gaur, founding director and Supreme Court advocate.",
    ],
  },
  {
    id: "nss",
    organization: "National Service Scheme, Hansraj College",
    role: "Volunteer",
    dates: "Nov 2022 – Sep 2023",
    initials: "NSS",
    description: "Volunteer experience in social-service activities.",
    highlights: [],
  },
];

export const education = [
  {
    institution: "Hansraj College, University of Delhi",
    degree: "B.Sc. (Hons. with Research), Computer Science",
    dates: "2022 – 2026",
    current: false,
  },
  {
    institution: "Lilawati Vidya Mandir Sr. Sec. School, Delhi",
    degree: "Senior Secondary / High School",
    dates: "2021 – 2022",
    current: false,
  },
  {
    institution: "Lilawati Vidya Mandir Sr. Sec. School, Delhi",
    degree: "Secondary School",
    dates: "2019 – 2020",
    current: false,
  },
];

export const training = [
  {
    title: "Cloud & DevOps",
    provider: "DUCAT India",
    type: "Professional Training",
    description: "Offline technical training course completed at DUCAT, followed by a DUCAT certificate. This is training, not a degree and not an AWS-issued certification.",
    certificate: "/public/images/certificates/ducat-cloud-computing-certificate.pdf",
  },
];

export const skills = {
  cloud: ["AWS"],
  devops: ["Git", "Jenkins", "Docker", "Kubernetes", "Terraform", "Ansible", "Grafana"],
  programming: ["C++", "Python", "SQL"],
  data: ["NumPy", "Pandas", "Power BI"],
  systems: ["Linux Administration"],
  tools: ["MS Office", "Canva", "Apexa-IQ"],
  business: ["Business Analysis", "Client Engagement", "Process Coordination", "Documentation", "Research", "Data Analysis"],
  soft: ["Leadership", "Communication", "Team Collaboration", "Stakeholder Coordination", "Team Management", "Problem Solving", "Analytical Thinking", "Presentation", "Organization"],
};

export const certifications = [
  { title: "ACORPORATE X — Letter of Recommendation", provider: "ACORPORATE X", status: "Letter of Recommendation", link: "https://drive.google.com/file/d/1pKG9ce0YVsKrkPaQ8Ovfj5cbqhoTA32b/view", image: "/public/images/certificates/acorporatex-certificate.png" },
  { title: "ZIGRAM Internship Certificate", provider: "ZIGRAM", status: "Internship Certificate", link: "https://drive.google.com/file/d/17Xn6Sx85T1r4S71qCoQvwrpQv7wp9Pry/view", image: "/public/images/certificates/zigram-certificate.png" },
  { title: "Blu Parrot Internship Certificate", provider: "Blu Parrot Ventures", status: "Internship Certificate", link: "https://drive.google.com/file/d/1_EoU474x5peZHKGggflO6hUU4ak1vjMF/view", image: "/public/images/certificates/blu-parrot-logo.png" },
  { title: "Best Poster Presentation", provider: "Hansraj College Research Display Week", status: "Award / Certificate", link: "https://drive.google.com/file/d/12N5Ref_IOIqQL0B2pbG_7PTkU83xBnYL/view", image: "/public/images/certificates/bestpostercerti.png" },
  { title: "Second Position — Research Display Week", provider: "Hansraj College, May 2026", status: "Research Recognition", link: "", image: "/public/images/certificates/research-display-certificate.jpeg" },
  { title: "CAS Head Certificate", provider: "Culinary Arts Society, Hansraj College", status: "Leadership Certificate", link: "https://drive.google.com/file/d/1XB5PWgOTH2370jeSjYp1VnLNKRAGxF2H/view", image: "/public/images/certificates/casheadcerti.png" },
  { title: "Smart India Hackathon Certificate", provider: "SIH", status: "Participation / Recognition", link: "https://drive.google.com/file/d/1IzBjW0kkwNN1TMKVVQIHK1qmmjsEta2O/view", image: "/public/images/certificates/sihcert.png" },
  { title: "SIH 2024 — College Round Certificate", provider: "Hansraj College", status: "College Round", link: "https://drive.google.com/file/d/1D1vbYPQ5TdbovFOlTT0Ff02ciuFyOQri/view", image: "/public/images/certificates/sih-hrc-cert.png" },
  { title: "Ehsaas College President Certificate", provider: "Ehsaas for Humanity Foundation", status: "Leadership Certificate", link: "https://drive.google.com/file/d/1ww2zeaePgJFe6cWQx-fnxbqeFBq5XPn1/view", image: "/public/images/certificates/ehsaas-prez-cert.png" },
  { title: "Ehsaas Letter of Recommendation", provider: "Ehsaas for Humanity Foundation", status: "Letter of Recommendation", link: "https://drive.google.com/file/d/1Onz797Ivpoav3KmaegQM1Am57Z01jWbd/view", image: "/public/images/certificates/ehsaas-lor.png" },
  { title: "DPBH Certificate", provider: "DPBH'23", status: "Certificate", link: "https://drive.google.com/file/d/1zwx1i3fZQNLk5KabBM-SIySFk71X7rZ1/view", image: "/public/images/certificates/dbphcert.png" },
  { title: "DUCAT Cloud Computing — Full", provider: "DUCAT School of AI", status: "Professional Training", link: "/public/images/certificates/ducat-cloud-computing-certificate.pdf", image: "/public/images/certificates/ducat-cloud-computing-certificate.pdf" },
  { title: "Apexa-IQ IT Asset Management Training", provider: "Apexa-IQ", status: "Professional Training", link: "https://drive.google.com/file/d/15qGeS2-pfEKDQcYnA2qYQ16DUaDBKC3b/view", image: "/public/images/certificates/apexa-cert.png" },
  { title: "Bitwise Magazine — Volume 5", provider: "Hansraj College", status: "Publication", link: "https://www.hansrajcollege.ac.in/uploads/studentscorner/magazine/bitwise/Final%20Bitwise%202024.pdf", image: "/public/images/certificates/bitwise-cert.png" },
  { title: "Huntit Out Certificate", provider: "Hansraj College", status: "Event Certificate", link: "/public/images/certificates/huntItOutCerti.pdf", image: "/public/images/certificates/huntItOutCerti.pdf" },
  { title: "NSS Certificate", provider: "National Service Scheme, Hansraj College", status: "Volunteer Certificate", link: "/public/images/certificates/nssCertificate.pdf", image: "/public/images/certificates/nssCertificate.pdf" },
  { title: "Ordinateur Certificate", provider: "The Computer Science Society, Hansraj College", status: "Leadership", link: "", image: "/public/images/certificates/ordi.jpeg" },
];

export const photoGallery = [
  { src: "/public/images/gallery/research-display-week.jpeg", title: "Research Display Week", note: "Rice disease detection and advisory system" },
  { src: "/public/images/gallery/research-presentation.jpeg", title: "Research Presentation", note: "Presenting dissertation work at Hansraj College" },
  { src: "/public/images/gallery/dissertation.jpeg", title: "Dissertation Complete", note: "A deep-learning project from research to report" },
  { src: "/public/images/gallery/research-award.jpeg", title: "Research Recognition", note: "Second position at Research Display Week" },
  { src: "/public/images/gallery/college-memories.jpeg", title: "College Memories", note: "Campus life at Hansraj College" },
  { src: "/public/images/gallery/campus.jpeg", title: "Campus Days", note: "A little pause between busy days" },
  { src: "/public/images/gallery/blu-parrot.jpeg", title: "Blu Parrot", note: "Internship memories" },
  { src: "/public/images/gallery/huntitout.jpeg", title: "Huntit Out", note: "Events, teams and college life" },
  { src: "/public/images/experience/united-airlines-1.jpeg", title: "United Airlines", note: "Workplace and team memories" },
  { src: "/public/images/experience/united-airlines-2.jpeg", title: "United Airlines Team", note: "Learning alongside the team" },
  { src: "/public/images/experience/united-airlines-3.jpeg", title: "United Airlines Office", note: "A workplace snapshot" },
  { src: "/public/images/experience/united-airlines-4.jpeg", title: "United Airlines", note: "A day at the office" },
];
